version: "3.9"
services:
  haproxy:
      container_name: haproxy
      environment:
          - CERT1=hubs.tobias-weiss.org
            #- CERT2=yoursite.com, www.yoursite.com
          - EMAIL=tobias@tobias-weiss.org
          - STAGING=false
      volumes:
          - 'letsencrypt:/etc/letsencrypt'
          - './haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg'
      ports:
          - '80:80'
          - '443:443'
      image: 'ghcr.io/tomdess/docker-haproxy-certbot:master'
  rsyslog:
      container_name: rsyslog
      environment:
          - TZ=UTC
      ports:
          - '514:514'
      image: 'rsyslog/syslog_appliance_alpine'
  db:
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
    image: "postgres:14-alpine"
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  dialog:
    build:
      context: .
      dockerfile: dockerfiles/dialog.Dockerfile
    environment:
      AUTH_KEY: /etc/perms.pub.pem
      HTTPS_CERT_FULLCHAIN: /etc/ssl/fullchain.pem
      HTTPS_CERT_PRIVKEY: /etc/ssl/privkey.pem
      INTERACTIVE: "false"
    ports:
      - "4443:4443"
    volumes:
      - dialog:/code
    working_dir: /code
  hubs-admin:
    build:
      context: .
      dockerfile: dockerfiles/hubs.Dockerfile
    command: npm run local
    environment:
      INTERNAL_HOSTNAME: hubs-admin
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:8989/admin.html"]
    platform: linux/amd64
    ports:
      - "8989:8989"
    volumes:
      - hubs:/code
    working_dir: /code/admin
  hubs-client:
    build:
      context: .
      dockerfile: dockerfiles/hubs.Dockerfile
    command: npm run local
    environment:
      INTERNAL_HOSTNAME: hubs-client
    healthcheck:
      start_period: 3m30s
      test: ["CMD", "curl", "-fk", "https://localhost:8080"]
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - hubs:/code
      - letsencrypt:/code/certs
    working_dir: /code
  hubs-storybook:
    build:
      context: .
      dockerfile: dockerfiles/hubs.Dockerfile
    command: npm run storybook
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://hubs.local:6006"]
    platform: linux/amd64
    ports:
      - "6006:6006"
    volumes:
      - hubs:/code
    working_dir: /code
  postgrest:
    build:
      context: .
      dockerfile: dockerfiles/postgrest.Dockerfile
  reticulum:
    container_name: reticulum
    build:
      context: ./services/reticulum
      dockerfile: TurkeyDockerfile
      target: dev
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_CREDENTIALS: postgres
      DB_HOST: db
      DIALOG_HOSTNAME: "hubs.local"
      DIALOG_PORT: 4443
      HUBS_ADMIN_INTERNAL_HOSTNAME: hubs-admin
      HUBS_CLIENT_INTERNAL_HOSTNAME: hubs-client
      POSTGREST_INTERNAL_HOSTNAME: postgrest
      SPOKE_INTERNAL_HOSTNAME: spoke
    volumes:
      - letsencrypt:/code/certs
      - reticulum:/code
      - retstorage:/code/storage/dev
  spoke:
    build:
      context: .
      dockerfile: dockerfiles/spoke.Dockerfile
    environment:
      CORS_PROXY_SERVER: "hubs-proxy.tobias-weiss.org"
      INTERNAL_HOSTNAME: spoke
    platform: linux/amd64
    ports:
      - "9090:9090"
    volumes:
      - spoke:/code
networks:
  default:
    name: mozilla-hubs
volumes:
  dialog:
  hubs:
  letsencrypt:
  pgdata:
  reticulum:
  retstorage:
  spoke:
x-mutagen:
  sync:
    defaults:
      ignore:
        paths:
          - ".DS_Store"
          - ".gitignore"
          - "/certs/"
          - "/node_modules/"
          - "package-lock.sha512"
        vcs: true
      mode: "two-way-resolved"
    dialog:
      alpha: ./services/dialog
      beta: "volume://dialog"
    hubs:
      alpha: ./services/hubs
      beta: "volume://hubs"
      ignore:
        paths:
          - "/admin/certs/"
          - "/admin/node_modules/"
    letsencrypt:
      alpha: ./haproxy/letsencrypt
      beta: "volume://letsencrypt"
    reticulum:
      alpha: ./services/reticulum
      beta: "volume://reticulum"
      ignore:
        paths:
          - "/_build/"
          - "/bin/"
          - "/storage/"
    spoke:
      alpha: ./services/spoke
      beta: "volume://spoke"
